<?php

namespace AppBundle\Repository;

/**
 * categoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoriasRepository extends \Doctrine\ORM\EntityRepository
{
}
